model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"
[projects."/Users/amatho/code/ndla/backend"]
trust_level = "trusted"

[projects."/Users/amatho/code/go/jwt-forward-auth"]
trust_level = "trusted"

[projects."/Users/amatho/code/ndla/editorial-frontend"]
trust_level = "trusted"

[projects."/Users/amatho/code/ndla/frontend-packages"]
trust_level = "trusted"

[projects."/Users/amatho/code/ndla/deploy"]
trust_level = "trusted"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.idea]
command = "npx"
args = ["-y", "mcp-remote", "http://localhost:64342/sse"]
env = { "IJ_MCP_SERVER_PORT" = "64342" }

[mcp_servers.aws_documentation]
command = "uvx"
args = ["awslabs.aws-documentation-mcp-server@latest"]
env = { "FASTMCP_LOG_LEVEL" = "ERROR", "AWS_DOCUMENTATION_PARTITION" = "aws" }

[mcp_servers.aws-knowledge-mcp]
url = "https://knowledge-mcp.global.api.aws"

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
